image: node:10.15-alpine

cache:
  paths:  
  - build

stages:
    - build
    - publish

build:        
    stage: build    
    script:
        - npm ci
        - npm run build

npm_publish:        
    stage: publish
    only:
        - master
    script:        
      - cp now.json build
      - npm i -g --unsafe-perm now
      - cd build
      - now --token=${NOW_TOKEN}
